spring:
  datasource:
    url: jdbc:postgresql://dpg-cpg998ect0pc73d9rcn0-a.singapore-postgres.render.com/to_do_0iac
    username: to_do_0iac
    password: HwWjCabh6N2ht3VCq2HdY8OBCzENnvF9
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 7dc0018914b8097bc7c8fd14cf1733913868e09a0c60dd9d59641b9c2321e4c4
      expiration: 7200000 # 2 hours

      refresh-token:
        secret-key: c3ca986f7e93efd4046ecc05782ae90c9d9b22f0aa0760d9643d1c5c8e406b30
        expiration: 604800000 # 7 days
